In [2]:
import pandas as pd



df = pd.read_csv('synthetic_retail_sales.csv')

# 1. remove duplicate rows
df = df.drop_duplicates()

# 2. clean Region column - remove spaces and fix casing
df['Region'] = df['Region'].str.strip().str.lower()
df['Region'] = df['Region'].replace({'nort': 'north', 'centrl': 'central'})
df['Region'] = df['Region'].str.title()

# 3. convert Date to proper date type
df['Date'] = pd.to_datetime(df['Date'])

# 4. fix negative prices - make them positive
df['Price'] = df['Price'].abs()

# 5. fill missing Quantity and Price with column average
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())
df['Price'] = df['Price'].fillna(df['Price'].mean())

df.to_csv('cleaned_output.csv', index=False)
print(df.shape)

(520, 7)

In [ ]:
df

,Date,CustomerID,ProductID,Quantity,Price,Region,PaymentMethod
0,2024-09-06,C0136,P0008,1.000000,1393.658571,North,Debit Card
1,2024-06-28,C0186,P0030,8.000000,940.870000,West,UPI
2,2024-03-26,C0031,P0001,7.000000,1138.180000,East,Cash
3,2024-08-10,C0061,P0017,7.719588,1334.450000,North,Cash
4,2024-12-05,C0047,P0009,14.000000,1758.410000,North,Credit Card
...,...,...,...,...,...,...,...
534,2024-09-09,C0122,P0034,3.000000,1630.840000,North,UPI
535,2024-08-11,C0115,P0032,7.000000,52.410000,East,Credit Card
536,2024-09-14,C0064,P0003,12.000000,106.690000,Central,Debit Card
538,2024-11-13,C0178,P0040,2.000000,152.060000,West,UPI
539,2024-10-09,C0054,P0021,5.000000,707.590000,South,Cash

In [7]:
df_indexed = df.reset_index(drop=True)
df_indexed.index = df_indexed.index + 1
display(df_indexed.head())

        Date CustomerID ProductID   Quantity        Price Region PaymentMethod
1 2024-09-06      C0136     P0008   1.000000  1393.658571  North    Debit Card
2 2024-06-28      C0186     P0030   8.000000   940.870000   West           UPI
3 2024-03-26      C0031     P0001   7.000000  1138.180000   East          Cash
4 2024-08-10      C0061     P0017   7.719588  1334.450000  North          Cash
5 2024-12-05      C0047     P0009  14.000000  1758.410000  North   Credit Card

In [8]:
df_indexed

,Date,CustomerID,ProductID,Quantity,Price,Region,PaymentMethod
1,2024-09-06,C0136,P0008,1.000000,1393.658571,North,Debit Card
2,2024-06-28,C0186,P0030,8.000000,940.870000,West,UPI
3,2024-03-26,C0031,P0001,7.000000,1138.180000,East,Cash
4,2024-08-10,C0061,P0017,7.719588,1334.450000,North,Cash
5,2024-12-05,C0047,P0009,14.000000,1758.410000,North,Credit Card
...,...,...,...,...,...,...,...
516,2024-09-09,C0122,P0034,3.000000,1630.840000,North,UPI
517,2024-08-11,C0115,P0032,7.000000,52.410000,East,Credit Card
518,2024-09-14,C0064,P0003,12.000000,106.690000,Central,Debit Card
519,2024-11-13,C0178,P0040,2.000000,152.060000,West,UPI
520,2024-10-09,C0054,P0021,5.000000,707.590000,South,Cash

In [10]:
df_indexed["Revenue"] = df["Quantity"] * df["Price"]

In [11]:
df_indexed

,Date,CustomerID,ProductID,Quantity,Price,Region,PaymentMethod,Revenue
1,2024-09-06,C0136,P0008,1.000000,1393.658571,North,Debit Card,7526.960000
2,2024-06-28,C0186,P0030,8.000000,940.870000,West,UPI,7967.260000
3,2024-03-26,C0031,P0001,7.000000,1138.180000,East,Cash,10301.403711
4,2024-08-10,C0061,P0017,7.719588,1334.450000,North,Cash,24617.740000
5,2024-12-05,C0047,P0009,14.000000,1758.410000,North,Credit Card,12528.090000
...,...,...,...,...,...,...,...,...
516,2024-09-09,C0122,P0034,3.000000,1630.840000,North,UPI,2898.780000
517,2024-08-11,C0115,P0032,7.000000,52.410000,East,Credit Card,2159.820000
518,2024-09-14,C0064,P0003,12.000000,106.690000,Central,Debit Card,508.710000
519,2024-11-13,C0178,P0040,2.000000,152.060000,West,UPI,3420.120000
520,2024-10-09,C0054,P0021,5.000000,707.590000,South,Cash,1083.450000

In [12]:
df_indexed['Month'] = df_indexed['Date'].dt.month
display(df_indexed.head())

,Date,CustomerID,ProductID,Quantity,Price,Region,PaymentMethod,Revenue,Month
1,2024-09-06,C0136,P0008,1.000000,1393.658571,North,Debit Card,7526.960000,9
2,2024-06-28,C0186,P0030,8.000000,940.870000,West,UPI,7967.260000,6
3,2024-03-26,C0031,P0001,7.000000,1138.180000,East,Cash,10301.403711,3
4,2024-08-10,C0061,P0017,7.719588,1334.450000,North,Cash,24617.740000,8
5,2024-12-05,C0047,P0009,14.000000,1758.410000,North,Credit Card,12528.090000,12

In [13]:
df_indexed['Month'] = df_indexed['Date'].dt.strftime('%B')
display(df_indexed.head())

,Date,CustomerID,ProductID,Quantity,Price,Region,PaymentMethod,Revenue,Month
1,2024-09-06,C0136,P0008,1.000000,1393.658571,North,Debit Card,7526.960000,September
2,2024-06-28,C0186,P0030,8.000000,940.870000,West,UPI,7967.260000,June
3,2024-03-26,C0031,P0001,7.000000,1138.180000,East,Cash,10301.403711,March
4,2024-08-10,C0061,P0017,7.719588,1334.450000,North,Cash,24617.740000,August
5,2024-12-05,C0047,P0009,14.000000,1758.410000,North,Credit Card,12528.090000,December

In [15]:
df_indexed['Region']

1        North
2         West
3         East
4        North
5        North
        ...
516      North
517       East
518    Central
519       West
520      South
Name: Region, Length: 520, dtype: object

In [16]:
df_indexed

,Date,CustomerID,ProductID,Quantity,Price,Region,PaymentMethod,Revenue,Month
1,2024-09-06,C0136,P0008,1.000000,1393.658571,North,Debit Card,7526.960000,September
2,2024-06-28,C0186,P0030,8.000000,940.870000,West,UPI,7967.260000,June
3,2024-03-26,C0031,P0001,7.000000,1138.180000,East,Cash,10301.403711,March
4,2024-08-10,C0061,P0017,7.719588,1334.450000,North,Cash,24617.740000,August
5,2024-12-05,C0047,P0009,14.000000,1758.410000,North,Credit Card,12528.090000,December
...,...,...,...,...,...,...,...,...,...
516,2024-09-09,C0122,P0034,3.000000,1630.840000,North,UPI,2898.780000,September
517,2024-08-11,C0115,P0032,7.000000,52.410000,East,Credit Card,2159.820000,August
518,2024-09-14,C0064,P0003,12.000000,106.690000,Central,Debit Card,508.710000,September
519,2024-11-13,C0178,P0040,2.000000,152.060000,West,UPI,3420.120000,November
520,2024-10-09,C0054,P0021,5.000000,707.590000,South,Cash,1083.450000,October

In [17]:
pd.read_csv('/content/cleaned_output.csv')

,Date,CustomerID,ProductID,Quantity,Price,Region,PaymentMethod
0,2024-09-06,C0136,P0008,1.000000,1393.658571,North,Debit Card
1,2024-06-28,C0186,P0030,8.000000,940.870000,West,UPI
2,2024-03-26,C0031,P0001,7.000000,1138.180000,East,Cash
3,2024-08-10,C0061,P0017,7.719588,1334.450000,North,Cash
4,2024-12-05,C0047,P0009,14.000000,1758.410000,North,Credit Card
...,...,...,...,...,...,...,...
515,2024-09-09,C0122,P0034,3.000000,1630.840000,North,UPI
516,2024-08-11,C0115,P0032,7.000000,52.410000,East,Credit Card
517,2024-09-14,C0064,P0003,12.000000,106.690000,Central,Debit Card
518,2024-11-13,C0178,P0040,2.000000,152.060000,West,UPI
519,2024-10-09,C0054,P0021,5.000000,707.590000,South,Cash